export interface MenuItem {
  name_ar: string;
  name_en: string;
  name_de: string;
  price: string;
  category_ar: string;
  category_en: string;
  category_de: string;
  description_ar: string;
  description_en: string;
  description_de: string;
  image?: string;
}

export const MENU_ITEMS: MenuItem[] = [
  {
    name_ar: "دبس فليفلة",
    name_en: "Spicy Pepper Paste",
    name_de: "Schärfepaste",
    price: "5€",
    category_ar: "المقبلات والسلطات",
    category_en: "Starters & Salads",
    category_de: "Vorspeisen & Beilage",
    description_ar: "مقبلات حارة لذيذة",
    description_en: "A spicy appetizer made from peppers.",
    description_de: "Würzige Vorspeise aus Paprika.",
    image: "https://i.imgur.com/wXyc5o3.png"
  },
  {
    name_ar: "متبل باذنجان",
    name_en: "Eggplant Dip",
    name_de: "Auberginen Paste",
    price: "5€",
    category_ar: "المقبلات والسلطات",
    category_en: "Starters & Salads",
    category_de: "Vorspeisen & Beilage",
    description_ar: "مقبلات باذنجان لذيذة",
    description_en: "Creamy eggplant dip with olive oil.",
    description_de: "Cremiger Auberginendip mit Olivenöl.",
    image: "https://i.imgur.com/XTI2ENE.png",
  },
  {
    name_ar: "حمص",
    name_en: "Hummus",
    name_de: "Hummus",
    price: "5€",
    category_ar: "المقبلات والسلطات",
    category_en: "Starters & Salads",
    category_de: "Vorspeisen & Beilage",
    description_ar: "حمص طازج مع زيت زيتون",
    description_en: "Fresh hummus topped with olive oil.",
    description_de: "Frischer Hummus mit Olivenöl.",
    image: "https://i.imgur.com/qeJ4yOj.png",
  },
  {
    name_ar: "كريم ثوم",
    name_en: "Garlic Sauce",
    name_de: "Knoblauchsauce",
    price: "5€",
    category_ar: "المقبلات والسلطات",
    category_en: "Starters & Salads",
    category_de: "Vorspeisen & Beilage",
    description_ar: "صلصة ثومية غنية",
    description_en: "Rich garlic sauce for dipping.",
    description_de: "Reichhaltige Knoblauchsauce zum Dippen.",
    image: "https://i.imgur.com/xuJmjzJ.png",
  },
  {
    name_ar: "طبق بطاطا مقلية مع كاتشب ومايونيز",
    name_en: "French Fries with Ketchup and Mayonnaise",
    name_de: "Pommesteller with Ketchup and Mayonnaise",
    price: "5€",
    category_ar: "المقبلات والسلطات",
    category_en: "Starters & Salads",
    category_de: "Vorspeisen & Beilage",
    description_ar: "طبق بطاطا مقلية مع الصوص",
    description_en: "Crispy fries served with sauces.",
    description_de: "Knusprige Pommes mit Saucen.",
    image: "https://i.imgur.com/wAFarKU.png",
  },
  {
    name_ar: "سلطة خضار مشكلة",
    name_en: "Mixed Vegetable Salad",
    name_de: "Gemischter Salat",
    price: "5€",
    category_ar: "المقبلات والسلطات",
    category_en: "Starters & Salads",
    category_de: "Vorspeisen & Beilage",
    description_ar: "سلطة طازجة متنوعة",
    description_en: "Fresh mixed salad with crisp vegetables.",
    description_de: "Frischer gemischter Salat mit knackigem Gemüse.",
    image: "https://i.imgur.com/lE5uZaf.png",
  },
  {
    name_ar: "سلطة ملفوف",
    name_en: "Cabbage Salad",
    name_de: "Krautsalat",
    price: "5€",
    category_ar: "المقبلات والسلطات",
    category_en: "Starters & Salads",
    category_de: "Vorspeisen & Beilage",
    description_ar: "سلطة ملفوف مقرمشة",
    description_en: "Crunchy cabbage salad with dressing.",
    description_de: "Knackiger Krautsalat mit Dressing.",
    image: "https://i.imgur.com/pHebSb1.png",
  },
  {
    name_ar: "ساندويش شاورما دجاج",
    name_en: "Chicken Shawarma Roll",
    name_de: "Hähnchen Shawarma Rolle",
    price: "7€",
    category_ar: "شاورما",
    category_en: "Shawarma",
    category_de: "Shawarma",
    description_ar: "رول شاورما دجاج طازج",
    description_en: "Fresh chicken shawarma wrapped in flatbread.",
    description_de: "Frische Hähnchen Shawarma in Fladenbrot.",
    image: "https://i.imgur.com/CSSn2e2.png"
  },
  {
    name_ar: "ساندويش شاورما دجاج مع لحم إضافي",
    name_en: "Chicken Shawarma Roll with Extra Meat",
    name_de: "Hähnchen Shawarma Rolle (Xtra Fleisch)",
    price: "9€",
    category_ar: "شاورما",
    category_en: "Shawarma",
    category_de: "Shawarma",
    description_ar: "شاورما دجاج مع لحم إضافي",
    description_en: "Extra meat for a heartier shawarma.",
    description_de: "Mit zusätzlichem Fleisch für mehr Genuss.",
    image: "https://i.imgur.com/t3dchwp.png",
  },
  {
    name_ar: "ساندويش شاورما دجاج مع جبنة إضافية",
    name_en: "Chicken Shawarma Roll with Extra Cheese",
    name_de: "Hähnchen Shawarma Rolle (Xtra mit Käse)",
    price: "8€",
    category_ar: "شاورما",
    category_en: "Shawarma",
    category_de: "Shawarma",
    description_ar: "شاورما دجاج مع جبنة إضافية",
    description_en: "Chicken shawarma with extra melted cheese.",
    description_de: "Hähnchen Shawarma mit extra Käse.",
    image: "https://i.imgur.com/tXkEP7L.png",
  },
  {
    name_ar: "شاورما دجاج 1 كيلو",
    name_en: "Chicken Shawarma (1kg)",
    name_de: "Hähnchen Shawarma (1kg)",
    price: "45€",
    category_ar: "شاورما",
    category_en: "Shawarma",
    category_de: "Shawarma",
    description_ar: "طبق شاورما دجاج 1 كيلو مع صوص",
    description_en: "1kg plate of chicken shawarma with sauce.",
    description_de: "1kg Hähnchen Shawarma mit Sauce.",
    image: "https://i.ibb.co/JWqqQMHr/1.png",
  },
  {
    name_ar: "شاورما دجاج نصف كيلو",
    name_en: "Chicken Shawarma (1/2kg)",
    name_de: "Hähnchen Shawarma (1/2kg)",
    price: "25€",
    category_ar: "شاورما",
    category_en: "Shawarma",
    category_de: "Shawarma",
    description_ar: "شاورما دجاج نصف كيلو",
    description_en: "Half kilo of chicken shawarma.",
    description_de: "Halbes Kilo Hähnchen Shawarma.",
    image: "https://i.ibb.co/qMpLktrz/image.png",
  },
  {
    name_ar: "طبق شاورما دجاج مع بطاطا، سلطة وصوص",
    name_en: "Chicken Shawarma Plate with Fries, Salad & Sauce",
    name_de: "Hähnchen Shawarma Teller",
    price: "13€",
    category_ar: "شاورما",
    category_en: "Shawarma",
    category_de: "Shawarma",
    description_ar: "طبق شاورما دجاج متكامل",
    description_en: "A complete plate featuring chicken shawarma.",
    description_de: "Komplettes Gericht mit Hähnchen Shawarma.",
    image: "https://i.imgur.com/KfrODmO.png",
  },
  {
    name_ar: "طبق شاورما دجاج عربي",
    name_en: "Arabian Chicken Shawarma Plate",
    name_de: "Hähnchen Shawarma (Arabische Teller)",
    price: "12€",
    category_ar: "شاورما",
    category_en: "Shawarma",
    category_de: "Shawarma",
    description_ar: "طبق شاورما دجاج عربي مع صوص",
    description_en: "Arab-style chicken shawarma plate.",
    description_de: "Arabisches Hähnchen Shawarma Gericht.",
    image: "https://i.imgur.com/KL5k1iY.png",
  },
  {
    name_ar: "بوكس شاورما دجاج كبير",
    name_en: "Large Chicken Shawarma Box",
    name_de: "Hähnchen Shawarmabox (Groß)",
    price: "8€",
    category_ar: "شاورما",
    category_en: "Shawarma",
    category_de: "Shawarma",
    description_ar: "بوكس شاورما دجاج كبير",
    description_en: "A large chicken shawarma box for sharing.",
    description_de: "Große Hähnchen Shawarma Box zum Teilen.",
    image: "https://i.imgur.com/KR4bjaP.png",
  },
  {
    name_ar: "بوكس شاورما دجاج صغير",
    name_en: "Small Chicken Shawarma Box",
    name_de: "Hähnchen Shawarmabox (Klein)",
    price: "6€",
    category_ar: "شاورما",
    category_en: "Shawarma",
    category_de: "Shawarma",
    description_ar: "بوكس شاورما دجاج صغير",
    description_en: "A small chicken shawarma box.",
    description_de: "Kleine Hähnchen Shawarma Box.",
    image: "https://i.imgur.com/FY2rgGT.png",
  },
  {
    name_ar: "ساندويش شاورما لحم",
    name_en: "Beef Shawarma Roll",
    name_de: "Fleisch Shawarma Rolle",
    price: "8€",
    category_ar: "فقط أيام السبت",
    category_en: "Saturday Only",
    category_de: "Nur Samstag",
    description_ar: "رول شاورما لحم خاص يوم السبت",
    description_en: "Special beef shawarma roll available on Saturdays.",
    description_de: "Besonderer Fleisch Shawarma Roll nur samstags.",
    image: "https://i.imgur.com/SgKM6iG.png",
  },
  {
    name_ar: "ساندويش شاورما لحم مع لحم إضافي",
    name_en: "Beef Shawarma Roll with Extra Meat",
    name_de: "Fleisch Shawarma Rolle (Xtra Fleisch)",
    price: "10€",
    category_ar: "فقط أيام السبت",
    category_en: "Saturday Only",
    category_de: "Nur Samstag",
    description_ar: "شاورما لحم مع لحم إضافي",
    description_en: "Beef shawarma roll with extra meat.",
    description_de: "Fleisch Shawarma mit extra Fleisch.",
    image: "https://i.imgur.com/lEQyNAi.png",
  },
  {
    name_ar: "شاورما لحم 1 كيلو",
    name_en: "Beef Shawarma (1kg)",
    name_de: "Fleisch Shawarma (1kg)",
    price: "50€",
    category_ar: "فقط أيام السبت",
    category_en: "Saturday Only",
    category_de: "Nur Samstag",
    description_ar: "شاورما لحم 1 كيلو",
    description_en: "1kg beef shawarma plate.",
    description_de: "1kg Fleisch Shawarma Platte.",
    image: "https://i.ibb.co/5hywQK3P/1.png",
  },
  {
    name_ar: "شاورما لحم نصف كيلو",
    name_en: "Beef Shawarma (1/2kg)",
    name_de: "Fleisch Shawarma (1/2kg)",
    price: "30€",
    category_ar: "فقط أيام السبت",
    category_en: "Saturday Only",
    category_de: "Nur Samstag",
    description_ar: "شاورما لحم نصف كيلو",
    description_en: "Half kilo beef shawarma.",
    description_de: "Halbes Kilo Fleisch Shawarma.",
    image: "https://i.ibb.co/Swpz3DCy/image.png",
  },
  {
    name_ar: "طبق شاورما لحم مع بطاطا، سلطة وصوص",
    name_en: "Beef Shawarma Plate with Fries, Salad & Sauce",
    name_de: "Fleisch Shawarma Teller (mit Pommes, Salat & Sauce)",
    price: "14€",
    category_ar: "فقط أيام السبت",
    category_en: "Saturday Only",
    category_de: "Nur Samstag",
    description_ar: "طبق شاورما لحم متكامل",
    description_en: "Complete beef shawarma plate with sides.",
    description_de: "Komplettes Fleisch Shawarma Gericht mit Beilagen.",
    image: "https://i.imgur.com/KC8NuYB.png",
  },
  {
    name_ar: "طبق شاورما عربي لحم",
    name_en: "Arabian Beef Shawarma Plate",
    name_de: "Fleisch Shawarma (Arabische Teller)",
    price: "13€",
    category_ar: "فقط أيام السبت",
    category_en: "Saturday Only",
    category_de: "Nur Samstag",
    description_ar: "طبق شاورما عربي لحم",
    description_en: "Arab-style beef shawarma plate.",
    description_de: "Arabisches Fleisch Shawarma Gericht.",
    image: "https://i.imgur.com/TS9sCXn.png",
  },
  {
    name_ar: "بوكس شاورما لحم كبير",
    name_en: "Large Beef Shawarma Box",
    name_de: "Fleisch Shawarmabox (Groß)",
    price: "9€",
    category_ar: "فقط أيام السبت",
    category_en: "Saturday Only",
    category_de: "Nur Samstag",
    description_ar: "بوكس شاورما لحم كبير",
    description_en: "Large beef shawarma box.",
    description_de: "Große Fleisch Shawarmabox.",
    image: "https://i.imgur.com/ja5AVGA.png",
  },
  {
    name_ar: "بوكس شاورما لحم صغير",
    name_en: "Small Beef Shawarma Box",
    name_de: "Fleisch Shawarmabox (Klein)",
    price: "7€",
    category_ar: "فقط أيام السبت",
    category_en: "Saturday Only",
    category_de: "Nur Samstag",
    description_ar: "بوكس شاورما لحم صغير",
    description_en: "Small beef shawarma box.",
    description_de: "Kleine Fleisch Shawarmabox.",
    image: "https://i.imgur.com/q07a8jJ.png",
  },
  {
    name_ar: "بروستد (فروج كامل مع بطاطا، سلطة و صوص)",
    name_en: "Fried Chicken (Whole)",
    name_de: "Fried Chicken (Ganz)",
    price: "24€",
    category_ar: "دجاج",
    category_en: "Chicken",
    category_de: "Hähnchen",
    description_ar: "فروج كامل مع بطاطا، سلطة وصوص",
    description_en: "Whole fried chicken with fries, salad and sauce.",
    description_de: "Ganze frittierte Hähnchen mit Pommes, Salat und Sauce.",
    image: "https://i.imgur.com/tiKmp3A.png",
  },
  {
    name_ar: "بروستد (نصف فروج مع بطاطا، سلطة و صوص)",
    name_en: "Fried Chicken (Half)",
    name_de: "Fried Chicken (Halb)",
    price: "12€",
    category_ar: "دجاج",
    category_en: "Chicken",
    category_de: "Hähnchen",
    description_ar: "نصف فروج بروستد مع المقبلات",
    description_en: "Half fried chicken with sides.",
    description_de: "Halbes frittiertes Hähnchen mit Beilagen.",
    image: "https://i.imgur.com/adrP5JZ.png",
  },
  {
    name_ar: "دجاج كرسبي",
    name_en: "Crispy Chicken",
    name_de: "Crispy Chicken",
    price: "12€",
    category_ar: "دجاج",
    category_en: "Chicken",
    category_de: "Hähnchen",
    description_ar: "ساندويش كرسبي أو طبق مقرمش",
    description_en: "Crispy chicken sandwich or plate.",
    description_de: "Knuspriges Hähnchen als Sandwich oder Teller.",
    image: "https://i.ibb.co/YFLsb0Pj/image.png",
  },
  {
    name_ar: "ساندويش كرسبي",
    name_en: "Crispy Chicken Roll",
    name_de: "Crispy Chicken Rolle",
    price: "7€",
    category_ar: "دجاج",
    category_en: "Chicken",
    category_de: "Hähnchen",
    description_ar: "رول دجاج كرسبي",
    description_en: "Crispy chicken wrapped in bread.",
    description_de: "Knuspriges Hähnchen in einer Rolle.",
    image: "https://i.imgur.com/f33GB5W.png",
  },
  {
    name_ar: "فروج كامل مشوي مع رز أو بطاطا، سلطة وصوص",
    name_en: "Whole Grilled Chicken with Rice or Fries, Salad & Sauce",
    name_de: "Gegrilltes Huhn (ganz)",
    price: "20€",
    category_ar: "دجاج",
    category_en: "Chicken",
    category_de: "Hähnchen",
    description_ar: "فروج مشوية كاملة",
    description_en: "Whole grilled chicken with sides.",
    description_de: "Ganze gegrillte Hähnchen mit Beilagen.",
    image: "https://i.imgur.com/Wwcara5.png",
  },
  {
    name_ar: "نصف فروج مشوي مع رز أو بطاطا، سلطة وصوص",
    name_en: "Half Grilled Chicken with Rice or Fries, Salad & Sauce",
    name_de: "Gegrilltes Huhn (halb)",
    price: "11€",
    category_ar: "دجاج",
    category_en: "Chicken",
    category_de: "Hähnchen",
    description_ar: "نصف فروج مشوي",
    description_en: "Half grilled chicken with sides.",
    description_de: "Halbes gegrilltes Hähnchen mit Beilagen.",
    image: "https://i.imgur.com/quYdcqm.png",
  },
  {
    name_ar: "الطبق السوري",
    name_en: "Syrian Platter",
    name_de: "Syrische Teller",
    price: "15€",
    category_ar: "أطباق مختلطة ومميزة",
    category_en: "Signature & Mixed Dishes",
    category_de: "Gemischte & Spezialitäten",
    description_ar: "طبق سوري مميز",
    description_en: "A signature Syrian-style mixed plate.",
    description_de: "Eine besondere syrische Mischung.",
    image: "https://i.ibb.co/PvszrQkC/image.png",
  },
  {
    name_ar: "الطبق المكسيكي (مع بطاطا مقلية وأرز وصوص)",
    name_en: "Mexican Platter (with Fries, Rice & Sauce)",
    name_de: "Mexikanische Teller",
    price: "12€",
    category_ar: "أطباق مختلطة ومميزة",
    category_en: "Signature & Mixed Dishes",
    category_de: "Gemischte & Spezialitäten",
    description_ar: "طبق مكسيكي مع بطاطا وأرز",
    description_en: "A Mexican-style plate with fries and rice.",
    description_de: "Mexikanischer Teller mit Pommes und Reis.",
    image: "https://i.imgur.com/Le4Przs.png",
  },
  {
    name_ar: "ساندويش مكسيكي",
    name_en: "Mexican Roll",
    name_de: "Mexikanische Rolle",
    price: "7€",
    category_ar: "أطباق مختلطة ومميزة",
    category_en: "Signature & Mixed Dishes",
    category_de: "Gemischte & Spezialitäten",
    description_ar: "رول مكسيكي",
    description_en: "A spicy Mexican-style roll.",
    description_de: "Würzige mexikanische Rolle.",
    image: "https://i.imgur.com/vNhjqS6.png",
  },
  {
    name_ar: "ساندويش مكسيكي مع إضافة جبنة",
    name_en: "Mexican Roll with Extra Cheese",
    name_de: "Mexikanische Rolle (Xtra mit Käse)",
    price: "8€",
    category_ar: "أطباق مختلطة ومميزة",
    category_en: "Signature & Mixed Dishes",
    category_de: "Gemischte & Spezialitäten",
    description_ar: "رول مكسيكي مع جبنة",
    description_en: "Mexican roll topped with extra cheese.",
    description_de: "Mexikanische Rolle mit extra Käse.",
    image: "https://i.ibb.co/ZzY42m7F/image.png",
  },
  {
    name_ar: "طبق كبدة دجاج",
    name_en: "Chicken Liver Plate",
    name_de: "Hähnchen Leber Teller",
    price: "12€",
    category_ar: "أطباق مختلطة ومميزة",
    category_en: "Signature & Mixed Dishes",
    category_de: "Gemischte & Spezialitäten",
    description_ar: "طبق كبدة دجاج مع صوص",
    description_en: "Chicken liver plate with sauce.",
    description_de: "Hähnchenleber Teller mit Sauce.",
    image: "https://i.imgur.com/FIBaqmd.png",
  },
  {
    name_ar: "ساندويش كبدة دجاج",
    name_en: "Chicken Liver Roll",
    name_de: "Hähnchen Leber Rolle",
    price: "7€",
    category_ar: "أطباق مختلطة ومميزة",
    category_en: "Signature & Mixed Dishes",
    category_de: "Gemischte & Spezialitäten",
    description_ar: "رول كبدة دجاج",
    description_en: "Chicken liver roll with spices.",
    description_de: "Hähnchenleber Rolle mit Gewürzen.",
    image: "https://i.imgur.com/dlVtlpv.png",
  },
  {
    name_ar: "طبق فلافل (مع سلطة وصوص)",
    name_en: "Falafel Plate (with Salad & Sauce)",
    name_de: "Falafel Teller",
    price: "10€",
    category_ar: "أطباق مختلطة ومميزة",
    category_en: "Signature & Mixed Dishes",
    category_de: "Gemischte & Spezialitäten",
    description_ar: "طبق فلافل مع صوص",
    description_en: "Falafel plate served with sauce.",
    description_de: "Falafel Teller mit Sauce.",
    image: "https://i.imgur.com/rxQDoFt.png",
  },
  {
    name_ar: "ساندويش فلافل",
    name_en: "Falafel Roll",
    name_de: "Falafel Rolle",
    price: "6€",
    category_ar: "أطباق مختلطة ومميزة",
    category_en: "Signature & Mixed Dishes",
    category_de: "Gemischte & Spezialitäten",
    description_ar: "رول فلافل",
    description_en: "Falafel wrapped in soft bread.",
    description_de: "Falafel in einer Rolle.",
    image: "https://i.imgur.com/Gatkf8S.png",
  },
  {
    name_ar: "كباب مشوي (سيخين مع رز و بطاطا و صوص)",
    name_en: "Grilled Kebab (2 Skewers with Rice, Fries & Sauce)",
    name_de: "gegrillte Kebab (2 Spieß)",
    price: "18€",
    category_ar: "مشاوي",
    category_en: "Grills",
    category_de: "Grillgerichte",
    description_ar: "كباب مشوي مع صوص",
    description_en: "Grilled kebab with sauce.",
    description_de: "Gegrillter Kebab mit Sauce.",
    image: "https://i.imgur.com/ml3sbvJ.png",
  },
  {
    name_ar: "ساندويش كباب مشوي",
    name_en: "Grilled Kebab Roll",
    name_de: "gegrillte Kebab Rolle",
    price: "10€",
    category_ar: "مشاوي",
    category_en: "Grills",
    category_de: "Grillgerichte",
    description_ar: "رول كباب مشوي",
    description_en: "Grilled kebab wrapped in bread.",
    description_de: "Gegrillter Kebab in einer Rolle.",
    image: "https://i.imgur.com/XfcHa2E.png",
  },
  {
    name_ar: "كباب مشوي 1 كيلو",
    name_en: "Grilled Kebab (1kg)",
    name_de: "gegrillte Kebab (1kg)",
    price: "55€",
    category_ar: "مشاوي",
    category_en: "Grills",
    category_de: "Grillgerichte",
    description_ar: "كباب مشوي 1 كيلو",
    description_en: "1kg grilled kebab plate.",
    description_de: "1kg gegrillter Kebab Teller.",
    image: "https://i.ibb.co/M5h2jt9H/image.png",
  },
  {
    name_ar: "كباب مشوي نصف كيلو",
    name_en: "Grilled Kebab (1/2kg)",
    name_de: "gegrillte Kebab (1/2kg)",
    price: "30€",
    category_ar: "مشاوي",
    category_en: "Grills",
    category_de: "Grillgerichte",
    description_ar: "كباب مشوي نصف كيلو",
    description_en: "Half kilo grilled kebab.",
    description_de: "Halbes Kilo gegrillter Kebab.",
    image: "https://i.ibb.co/KjJG7RSG/image.png",
  },
  {
    name_ar: "مشاوي مشكلة (3 أسياخ مع رز أو بطاطا، سلطة وصوص)",
    name_en: "Mixed Grill Platter (3 Skewers with Rice or Fries, Salad & Sauce)",
    name_de: "Gemischte Grillteller (3 Spieß)",
    price: "22€",
    category_ar: "مشاوي",
    category_en: "Grills",
    category_de: "Grillgerichte",
    description_ar: "طبق مشاوي مشكلة",
    description_en: "Mixed grill platter with three skewers.",
    description_de: "Gemischte Grillplatte mit drei Spießen.",
    image: "https://i.imgur.com/emn4rel.png",
  },
  {
    name_ar: "مشاوي مشكلة 1 كيلو",
    name_en: "Mixed Grill (1kg)",
    name_de: "Gemischte Grill (1kg)",
    price: "60€",
    category_ar: "مشاوي",
    category_en: "Grills",
    category_de: "Grillgerichte",
    description_ar: "مشاوي مشكلة 1 كيلو",
    description_en: "1kg mixed grill for sharing.",
    description_de: "1kg gemischter Grill zum Teilen.",
    image: "https://i.ibb.co/Tx42WHnT/image.png",
  },
  {
    name_ar: "مشاوي مشكلة نصف كيلو",
    name_en: "Mixed Grill (1/2kg)",
    name_de: "Gemischte Grill (1/2kg)",
    price: "35€",
    category_ar: "مشاوي",
    category_en: "Grills",
    category_de: "Grillgerichte",
    description_ar: "مشاوي مشكلة نصف كيلو",
    description_en: "Half kilo mixed grill.",
    description_de: "Halbes Kilo gemischter Grill.",
    image: "https://i.ibb.co/sdQ49fxW/image.png",
  },
  {
    name_ar: "كباب باذنجان (2 سيخ مع رز أو بطاطا مقلية، سلطة وصوص)",
    name_en: "Aubergine Kebab (2 Skewers with Rice or Fries, Salad & Sauce)",
    name_de: "Auberginen Kebab (2 Spieß mit Reis/Pommes, Salat & Sauce)",
    price: "18€",
    category_ar: "مشاوي",
    category_en: "Grills",
    category_de: "Grillgerichte",
    description_ar: "كباب باذنجان مع صوص",
    description_en: "Eggplant kebab served with sauce.",
    description_de: "Auberginen Kebab mit Sauce.",
    "image":"https://i.imgur.com/DaPz4uf.png",
  },
  {
    name_ar: "كباب باذنجان (1 كيلو)",
    name_en: "Aubergine Kebab (1kg)",
    name_de: "Auberginen Kebab (1kg)",
    price: "55€",
    category_ar: "مشاوي",
    category_en: "Grills",
    category_de: "Grillgerichte",
    description_ar: "كباب باذنجان 1 كيلو",
    description_en: "1kg eggplant kebab plate.",
    description_de: "Auberginen Kebab Platte (1kg).",
    image: "https://i.ibb.co/dsMV8D2j/image.png",
  },
  {
    name_ar: "كباب باذنجان (نصف كيلو)",
    name_en: "Aubergine Kebab (1/2kg)",
    name_de: "Auberginen Kebab (1/2kg)",
    price: "30€",
    category_ar: "مشاوي",
    category_en: "Grills",
    category_de: "Grillgerichte",
    description_ar: "كباب باذنجان نصف كيلو",
    description_en: "Half kilo eggplant kebab.",
    description_de: "Auberginen Kebab (1/2kg).",
    image: "https://i.ibb.co/YBG3j0p0/image.png",
  },
  {
    name_ar: "أسياخ شيش طاووق (2 سيخ مع رز أو بطاطا مقلية، سلطة وصوص)",
    name_en: "Grilled Chicken Skewers (2 Skewers with Rice or Fries, Salad & Sauce)",
    name_de: "Gegrillte Hähnchenspieß (2 Spieß mit Reis/Pommes, Salat & Sauce)",
    price: "15€",
    category_ar: "مشاوي",
    category_en: "Grills",
    category_de: "Grillgerichte",
    description_ar: "أسياخ شيش طاووق مع صوص",
    description_en: "Grilled chicken skewers served with sauce.",
    description_de: "Gegrillte Hähnchenspieß mit Sauce.",
    image: "https://i.imgur.com/9aDS2Bo.png",
  },
  {
    name_ar: "ساندويش شيش طاووق",
    name_en: "Grilled Chicken Skewer Roll",
    name_de: "Gegrillte Hähnchenspieß Rolle",
    price: "9€",
    category_ar: "مشاوي",
    category_en: "Grills",
    category_de: "Grillgerichte",
    description_ar: "رول شيش طاووق",
    description_en: "Grilled chicken skewer wrapped in bread.",
    description_de: "Gegrillte Hähnchenspieß in einer Rolle.",
    image: "https://i.imgur.com/9s23jjw.png",
  },
  {
    name_ar: "شيش طاووق (1 كيلو)",
    name_en: "Grilled Chicken Skewers (1kg)",
    name_de: "Gegrillte Hähnchenspieß (1kg)",
    price: "45€",
    category_ar: "مشاوي",
    category_en: "Grills",
    category_de: "Grillgerichte",
    description_ar: "شيش طاووق 1 كيلو",
    description_en: "1kg grilled chicken skewers.",
    description_de: "Gegrillte Hähnchenspieß (1kg).",
    image: "https://i.ibb.co/994JQLQz/image.png",
  },
  {
    name_ar: "شيش طاووق (نصف كيلو)",
    name_en: "Grilled Chicken Skewers (1/2kg)",
    name_de: "Gegrillte Hähnchenspieß (1/2kg)",
    price: "25€",
    category_ar: "مشاوي",
    category_en: "Grills",
    category_de: "Grillgerichte",
    description_ar: "شيش طاووق نصف كيلو",
    description_en: "Half kilo grilled chicken skewers.",
    description_de: "Gegrillte Hähnchenspieß (1/2kg).",
    image: "https://i.ibb.co/XkscsmJj/image.png",
  },
  {
    name_ar: "لحم غنم مشوي (2 سيخ مع رز أو بطاطا مقلية، سلطة وصوص)",
    name_en: "Grilled Lamb (2 Skewers with Rice or Fries, Salad & Sauce)",
    name_de: "Gegrillte Schafffleisch (2 Spieß mit Reis/Pommes, Salat & Sauce)",
    price: "18€",
    category_ar: "مشاوي",
    category_en: "Grills",
    category_de: "Grillgerichte",
    description_ar: "لحم غنم مشوي مع صوص",
    description_en: "Grilled lamb served with sauce.",
    description_de: "Gegrillte Schafffleisch mit Sauce.",
    image: "https://i.imgur.com/nvohLk9.png",
  },
  {
    name_ar: "ساندويش لحم غنم مشوي",
    name_en: "Grilled Lamb Roll",
    name_de: "Gegrillte Schafffleisch Rolle",
    price: "10€",
    category_ar: "مشاوي",
    category_en: "Grills",
    category_de: "Grillgerichte",
    description_ar: "رول لحم غنم مشوي",
    description_en: "Grilled lamb wrapped in bread.",
    description_de: "Gegrillte Schafffleisch Rolle.",
    image: "https://i.imgur.com/jpSuFAf.png",
  },
  {
    name_ar: "لحم غنم مشوي (1 كيلو)",
    name_en: "Grilled Lamb (1kg)",
    name_de: "Gegrillte Schafffleisch (1kg)",
    price: "75€",
    category_ar: "مشاوي",
    category_en: "Grills",
    category_de: "Grillgerichte",
    description_ar: "لحم غنم مشوي 1 كيلو",
    description_en: "1kg grilled lamb.",
    description_de: "Gegrillte Schafffleisch (1kg).",
    image: "https://i.ibb.co/MyS09HWc/image.png",
  },
  {
    name_ar: "لحم غنم مشوي (نصف كيلو)",
    name_en: "Grilled Lamb (1/2kg)",
    name_de: "Gegrillte Schafffleisch (1/2kg)",
    price: "40€",
    category_ar: "مشاوي",
    category_en: "Grills",
    category_de: "Grillgerichte",
    description_ar: "لحم غنم مشوي نصف كيلو",
    description_en: "Half kilo grilled lamb.",
    description_de: "Gegrillte Schafffleisch (1/2kg).",
    image: "https://i.ibb.co/S4HNJxfq/image.png",
  }
];
